cli test to use make

diff --git a/bin/command_line_test b/bin/command_line_test
--- a/bin/command_line_test
+++ b/bin/command_line_test
@@ -16,16 +16,16 @@ summary_test() {
     fi
 }
 
-cutbox=build/Release/cutbox
+cutbox_cli=cutbox_command/build/Release/cutbox
 
-cd cutbox_command || exit 1
-xcodebuild || exit 1
+make -f cutbox_command/Makefile -C cutbox_command build || exit 1
 
-if [[ ! -e $cutbox ]]; then
+if [[ ! -e $cutbox_cli ]]; then
+    echo "Error: cutbox cli command not built" 1>&2
     exit 1
 fi
 
-github_summary "$($cutbox --help)"
+github_summary "$($cutbox_cli --help)"
 
 date_hour_ago=$(TZ=UTC gdate -d "-1 hour" +%Y-%m-%dT%H:%M:%SZ)
 date_day_ago=$(TZ=UTC gdate -d "-1 day" +%Y-%m-%dT%H:%M:%SZ)
@@ -42,54 +42,54 @@ github_summary \
 
 summary_test \
 "- \`cutbox\`" \
-"$($cutbox)" \
+"$($cutbox_cli)" \
 "Test Passed?
 Copied Text
 Copied text"
 
 summary_test "\`cutbox --fuzzy text\`" \
-"$($cutbox --fuzzy text)" \
+"$($cutbox_cli --fuzzy text)" \
 "Copied text"
 
 summary_test "\`cutbox --fuzzy zoo\`" \
-"$($cutbox --fuzzy zoo)" \
+"$($cutbox_cli --fuzzy zoo)" \
 ""
 
 summary_test "\`cutbox --regex Text\`" \
-"$($cutbox --regex Text)" \
+"$($cutbox_cli --regex Text)" \
 "Copied Text"
 
 summary_test "\`cutbox --regexi Text\`" \
-"$($cutbox --regexi Text)" \
+"$($cutbox_cli --regexi Text)" \
 "Copied Text
 Copied text"
 
 summary_test "\`cutbox --favorites\`" \
-"$($cutbox --favorites)" \
+"$($cutbox_cli --favorites)" \
 "Test Passed?"
 
 summary_test "\`cutbox --missing-date\`" \
-"$($cutbox --missing-date)" \
+"$($cutbox_cli --missing-date)" \
 "Test Passed?"
 
 summary_test "\`cutbox --since 61mins\`" \
-"$($cutbox --since 61mins)" \
+"$($cutbox_cli --since 61mins)" \
 "Test Passed?
 Copied Text"
 
 summary_test "\`cutbox --since 1.1day\`" \
-"$($cutbox --since 1.1day)" \
+"$($cutbox_cli --since 1.1day)" \
 "Test Passed?
 Copied Text
 Copied text"
 
 summary_test "\`cutbox --before 1.1hour\`" \
-"$($cutbox --before 1.1hour)" \
+"$($cutbox_cli --before 1.1hour)" \
 "Test Passed?
 Copied text"
 
 summary_test "\`cutbox --before 1.1day\`" \
-"$($cutbox --before 1.1day)" \
+"$($cutbox_cli --before 1.1day)" \
 "Test Passed?"
 
 [[ "$(grep "☠" "$GITHUB_STEP_SUMMARY")" == "" ]]  ||  exit 1
