Exit 1 on fail of command line test

diff --git a/.github/workflows/command_test.yml b/.github/workflows/command_test.yml
--- a/.github/workflows/command_test.yml
+++ b/.github/workflows/command_test.yml
@@ -22,4 +22,7 @@ jobs:
           test_bin/cutbox -h
           if [ $? == 0 ]; then
             echo "cutbox_command Test passed"
+          else
+            echo "cutbox_command Test failed"
+            exit 1
           fi
