App coverage reports to pages

diff --git a/.github/workflows/xcode-build.yml b/.github/workflows/xcode-build.yml
--- a/.github/workflows/xcode-build.yml
+++ b/.github/workflows/xcode-build.yml
@@ -60,14 +60,21 @@ jobs:
         run: |
           make test_ci
 
-      - name: Upload Test Coverage to Codacy
+      - name: Upload Test Coverage to Codacy and CutBox.github.io
         run: |
           if bin/codacy_upload_coverage; then
             echo "### Code coverage uploaded to Codacy [✓]" >> "$GITHUB_STEP_SUMMARY"
           else
             echo "### Failed uploaded to Codacy [✗]" >> "$GITHUB_STEP_SUMMARY"
+            exit 1
           fi
-          exit 0
+
+          if bin/pages_prepare_coverage_report; then
+            echo "### Code coverage prepared for to cutbox.github.io/CutBox/App/ [✓]" >> "$GITHUB_STEP_SUMMARY"
+          else
+            echo "### Failed prepare coverage for cutbox.github.io/CutBox/App/ [✗]" >> "$GITHUB_STEP_SUMMARY"
+            exit 1
+          fi
 
       - name: Check Localized.strings
         run: |
@@ -102,7 +109,7 @@ jobs:
           cp docs/customized.css docs/style.css
           bin/fix_llvm_html_pathnames docs cutbox_command
 
-      - name: CLI Coverage Report to cutbox.github.io/CutBox/coverage
+      - name: Push Coverage Reports to cutbox.github.io/CutBox/
         run: |
           git add docs
           if git diff --cached --quiet; then
@@ -110,8 +117,6 @@ jobs:
           else
             echo "Commit coverage report on docs/coverage"
             git commit -m "Update Pages - cli coverage - $(TZ=UTC date +%Y-%m-%dT%H:%M:%SZ) [codacy skip]"
-            git pull --rebase --autostash
-            git push
           fi
 
       - name: CLI Build
