Update xcode-build.yml

diff --git a/.github/workflows/xcode-build.yml b/.github/workflows/xcode-build.yml
--- a/.github/workflows/xcode-build.yml
+++ b/.github/workflows/xcode-build.yml
@@ -18,6 +18,14 @@ jobs:
           submodules: true
           fetch-depth: 0
           ref: master
+          
+      - name: Cache Go deps
+        uses: gacts/setup-go-with-cache@v1
+        with:
+          go-version: 1.19
+
+      - name: Install jv (JSON validator) (golang dep)
+        run: go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
 
       - name: CI diagnostics
         run: |
@@ -27,7 +35,7 @@ jobs:
             if [[ -x bin/$b ]]; then
               echo "[✓] bin/$b executable."
             else
-              echo "[❌] bin/$b - missing or non-executable" && exit 1
+              echo "[✗] bin/$b - missing or non-executable" && exit 1
             fi
           done
 
